name: Python unittest

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.3.1    
    - uses: actions/cache@v2
      id: cache-venv
      with:
        path: ./venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('./requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    - run: python -m venv ./venv && source ./venv/bin/activate && pip install -r requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'
    - run: source ./venv/bin/activate && pytest
